version: "2"

services:
    dev:
        build: .
        privileged: true
        container_name: x11-dev
        environment:
            - LANG=ja_JP.UTF-8
        volumes:
            - /run/udev:/run/udev
            - /etc/localtime:/etc/localtime:ro
            - /etc/locale.gen:/etc/locale.gen:ro
            - /usr/lib/locale/locale-archive:/usr/lib/locale/locale-archive:ro
            - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
            # x11-home
            - $HOME/x11-home/config:/home/user/.config
            - $HOME/x11-home/local:/home/user/local
            - $HOME/x11-home/work:/home/user/work
            - $HOME/x11-home/Downloads:/home/user/Downloads
            - $HOME/x11-home/Pictures:/home/user/Pictures
            # SETUP
            - $PWD/xinitrc.docker:/home/user/.xinitrc.docker
            - $PWD/install:/home/user/local/install
            # HOME
            - $HOME/.ssh:/home/user/.ssh
            - $HOME/.gitconfig.local:/home/user/.gitconfig.local
